version: '3'

services:
  base-yay:
    image: base-yay
    build:
      context: .
      dockerfile: ./services/base-yay/Dockerfile
  useful:
    image: useful
    build:
      context: .
      dockerfile: ./services/useful/Dockerfile
      args:
        - USER_NAME=${USER}
        - HOST_HOME=${HOME}
        - GITHUB_USER_NAME=${GITHUB_USER_NAME}
    depends_on:
      - base-yay
